services:
  # Backend API service
  - type: web
    name: student-management-backend
    env: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080

  # Frontend service
  - type: web
    name: student-management-frontend
    env: static
    plan: free
    buildCommand: chmod +x build-frontend.sh && ./build-frontend.sh
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://student-management-backend.onrender.com 