services:
  # Backend API service
  - type: web
    name: student-management-backend
    env: node
    plan: free
    buildCommand: pwd && ls -la && cd backend && pwd && ls -la && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080

  # Frontend service
  - type: web
    name: student-management-frontend
    env: static
    plan: free
    buildCommand: pwd && ls -la && cd frontend && pwd && ls -la && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://student-management-backend.onrender.com 